# Generated by Django 6.0.6 on 2026-08-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="enrollment_date",
        ),
        migrations.AddField(
            model_name="student",
            name="city",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
