# Generated by Django 6.0.6 on 2026-09-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="Category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
