# Generated by Django 6.0.6 on 2026-09-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="Category",
            new_name="category",
        ),
    ]
